// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"api_book/app"
	"api_book/controller"
	"api_book/middleware"
	"api_book/repository"
	"api_book/service"
	"github.com/google/wire"
	"net/http"
)

// Injectors from injector.go:

func InitializedServer() *http.Server {
	categoryRepository := repository.NewCategoryRepository()
	db := app.NewDB()
	validate := app.NewValidator()
	categoryService := service.NewCategoryService(categoryRepository, db, validate)
	categoryController := controller.NewCategoryController(categoryService)
	bookRepository := repository.NewBookRepository()
	logger := app.NewLogger()
	bookService := service.NewBookService(bookRepository, db, validate, logger)
	bookController := controller.NewBookController(bookService)
	router := app.NewRouter(categoryController, bookController)
	authMiddleware := middleware.NewAuthMiddleware(router)
	server := app.NewServer(authMiddleware)
	return server
}

// injector.go:

var categorySet = wire.NewSet(repository.NewCategoryRepository, service.NewCategoryService, controller.NewCategoryController)

var bookSet = wire.NewSet(repository.NewBookRepository, service.NewBookService, controller.NewBookController)
